In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2, activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:
model.get_weights()

[array([[-0.77881736,  0.94075143],
        [ 0.7342465 , -1.0544152 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.111518 ],
        [-0.4961267]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights = [np.array([[0.1,0.1],
                         [0.1,0.1]], dtype=np.float32),
               np.array([0.,0.], dtype=np.float32),
               np.array([[0.1],
                         [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [12]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 4ms/step - loss: 27.8873
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 27.5578
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 27.2598
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 26.8957
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 26.5637
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 26.1765
Epoch 7/75
4/4 [==============================] - 0s 4ms/step - loss: 25.8460
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 25.4255
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 25.0738
Epoch 10/75
4/4 [==============================] - 0s 4ms/step - loss: 24.6385
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 24.2173
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 23.8068
Epoch 13/75
4/4 [==============================] - 0s 3ms/ste

In [13]:
model.get_weights()

[array([[0.37367857, 0.37367857],
        [0.3658057 , 0.3658057 ]], dtype=float32),
 array([0.27244872, 0.27244872], dtype=float32),
 array([[0.37306702],
        [0.37306702]], dtype=float32),
 array([0.20492566], dtype=float32)]